### PR TITLE
Tests fix

### PR DESCRIPTION
**Pull request by cecastosic**
It would be great if there is a possibility to put specific id on the apply form, for example, id="apply-form" that can be used for cypress tests
In general comment, the best practice is to use name attributes, but in this form names are same as ids (and changeable) so I just used ids.

### CODE REVIEW

**Review by benna100 — COMMENTED** [review]
Have you tried to find the label with the text and then with that reference find the input element?

Something along this line
`.find('p').contains('Last Name').child('input')`

**Comment by cecastosic** [comment]
> .find('p').contains('Last Name').child('input')

This will not work 
Screenshot 2020-11-12 at 22 19 48

Since the structure is 
Screenshot 2020-11-12 at 22 20 53

and I don't think we need to find input, label also works (without classes also)
      .find('label')
      .contains('Last Name')
      .click()
      .type('Test Last Name')

But the problem is with radio buttons that contain text that is not unique (as Yes). I made a new commit and in it using input name ... and removed using classes and ids in the form.

**Review by benna100 — APPROVED** [review]
Nice, good job. This should work next time we have an application

**Comment by benna100** [comment]
Thanks for this!

**Pull request merged**
