### PR TITLE
Add Mohammad Info

### PR DESCRIPTION
**Pull request by myshuker**

### CODE REVIEW

**Review by dpfernandes — CHANGES_REQUESTED** [review]
Please change from "wordpress" to "Wordpress" so we avoid duplicates

**Comment by myshuker** [comment]
> Please change from "wordpress" to "Wordpress" so we avoid duplicates

Done. 
Thanks Daniel

**Review by dpfernandes — APPROVED** [review]
👍

**Comment by myshuker** [comment]
Hey Daniel
after you accept this PR and merget it to develop, why I cant see my profil in hire page?
thanks in advanced

**Comment by dpfernandes** [comment]
Have you checked Slack lately? @myshuker

**Pull request merged**
