### PR TITLE
added cv, photo and updated json file with details

### PR DESCRIPTION
**Pull request by sowmya1408**

### CODE REVIEW

**Review by dpfernandes — CHANGES_REQUESTED** [review]
@sowmya1408 You wrote 34 on the id and @MirSzabo and @rufaidaju already made a PR with 34 and 35 so maybe you want to change it to 36

**Comment by sowmya1408** [comment]
> @sowmya1408 You wrote 34 on the id and @MirSzabo and @rufaidaju already made a PR with 34 and 35 so maybe you want to change it to 36

>@dpfernandes  changed the id to 36 :)

**Review by dpfernandes — APPROVED** [review]
@benna100 I think this one is a go 👍

**Comment by benna100** [comment]
I have gotten you into develop

We had some problems with another branch, which is why this is being closed

**Pull request closed without merging**
