### PR TITLE
details added to the alumni repo to create my profile

### PR DESCRIPTION
**Pull request by amjadiftikhar**

### CODE REVIEW

**Comment by Laila1222** [comment]
It looks like the whole alumni.json file has been changed (unassumingly) due to some code formatter. 
I will leave the decision if it's okay to those people in charge in this project. :-)

Otherwise looks good, and works as it should! 👍

**Comment by amjadiftikhar** [comment]
> You need to only add changes that affect you. You have changed the file completely. If it is your linter that is cousing problems, only add the lines that affect you in the json file

I just edited and I added, what I was supposed to add in the file but I don't know if due to any formatter unexpected changed have been made. So what should I do now?

**Comment by benna100** [comment]
You need to revert your latest commit and then only add the information relevant to you. Do you know how to do that?

**Comment by amjadiftikhar** [comment]
> You need to revert your latest commit and then only add the information relevant to you. Do you know how to do that?

Yes I know, how to revert it but when I make comparison between these two versions of the alumni.json, I notice nothing changed but only the ID-32 added and its true that it shows as the whole file has been changed. I got through the whole file line by line by comparing red marked file (previous version) and green marked file (edited version) but looks same. If I revert this commit and try to commit it again, then result would the same, don't you think so?

**Comment by benna100** [comment]
Yes, if you just add the same it will be. Therefore you have to add only the lines where the information regarding you is contained. In git you can add specific lines. Use the visual studio Code Source control for this

**Pull request closed without merging**
