### PR TITLE
DeeptiSharma profile as of 18-feb-2021

### PR DESCRIPTION
**Pull request by Deepti-Dk**
Skills, Pic and CV added for Hire section
added on: 18-feb-2021

### CODE REVIEW

**Review by AnilMula — APPROVED** [review]
Perfect

**Comment by AnilMula** [comment]
Good

**Review by dpfernandes — CHANGES_REQUESTED** [review]
We need to have the same text for existing skills. For example "Asp.net MVC5", already exists so you need to replace your skill "ASP.NET MVC5", for "Asp.net MVC5" or else we will have duplicates.

**Comment by dpfernandes** [comment]
@AnilMula Please always check passed PR reviews from the project that you are reviewing the PR for.

**Review by AnilMula — APPROVED** [review]

**Review by dpfernandes — APPROVED** [review]
👍

**Comment by dpfernandes** [comment]
I reverted the PR. Please make a new one.

**Pull request merged**
