### PR TITLE
Anil profile is added to hire section

### PR DESCRIPTION
**Pull request by AnilMula**

### CODE REVIEW

**Review by Deepti-Dk — APPROVED** [review]
Looks good

**Review by Yaser-Aldammad — APPROVED** [review]

**Review by dpfernandes — CHANGES_REQUESTED** [review]
We already have the skill "Node.js", so you need to rename your skill  "NodeJs" for "Node.js" or else we will have duplicates

**Comment by dpfernandes** [comment]
@Deepti-Dk  Please always check passed PR reviews from the project that you are reviewing the PR for.

**Comment by dpfernandes** [comment]
@Yaser-Aldammad  Please always check passed PR reviews from the project that you are reviewing the PR for.

**Review by Deepti-Dk — APPROVED** [review]

**Comment by dpfernandes** [comment]
@AnilMula - Please aim your PR towards develop

**Comment by AnilMula** [comment]
should not be in master

**Pull request closed without merging**
